[package]
name = "ydjr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
matroska = "0.28.0"
serde = "1.0.215"
serde_json = "1.0.132"
