FROM rust:1.97 AS builder
WORKDIR /usr/src/ydjr
COPY . .
ENV SQLX_OFFLINE=true
RUN cargo build --release

FROM archlinux/archlinux
RUN pacman-key --init && pacman -Sy --noconfirm archlinux-keyring && pacman -S --noconfirm libmediainfo
COPY --from=builder /usr/src/ydjr/target/release/ydjr /usr/local/bin/ydjr
WORKDIR /mnt
CMD ["ydjr"]
