FROM rust:trixie AS builder
WORKDIR /usr/src/ydjr
COPY . .
ENV SQLX_OFFLINE=true
RUN cargo build --release

FROM debian:trixie-slim
COPY --from=builder /usr/src/ydjr/target/release/ydjr /usr/local/bin/ydjr
RUN apt update && apt install -y libmediainfo0v5 && rm -rf /var/lib/apt/lists/*
ENV LC_ALL=C.UTF-8
WORKDIR /mnt
CMD ["ydjr"]
