name: GitHub Actions containerization
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-container:
    name: Build & push container image to ghcr.io
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read # to fetch the repository content
      packages: write
      attestations: write
      id-token: write # for signing attestations and cache entries with GitHub OIDC
    with:
      output: image
      cache: true
      cache-mode: max
      push: true
      # Thanks to this we no longer have to sanitize the name beforehand:
      # https://github.com/docker/github-builder/pull/169
      meta-images: ghcr.io/${{ github.repository }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
